server:
  port: 8091
  servlet:
    context-path: /jwt-api

spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy

jwt:
  private-key-file-path: classpath:certificates/private.key
  public-cert-file-path: classpath:certificates/public.cert
  key-id: some-key-id
  # 2 hours
  expiration-time: 7200000
