server:
  port: 8090
  servlet:
    context-path: /security-example

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8091/jwt-api/authentication/jwks

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
